[window]
opacity = 0.9
blur = true

[font]
size = 11

normal = { family = 'JetBrains Mono NL NF', style ='normal' }
bold = { family = 'JetBrains Mono NL NF', style ='bold' }
italic = { family = 'JetBrains Mono NL NF', style ='italic' }
bold_italic = { family = 'JetBrains Mono NL NF', style = 'bold_italic' }

#https://github.com/alacritty/alacritty-theme/blob/master/themes/gruvbox_dark.toml

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
