[window]
opacity = 0.9
blur = true

[font]
size = 11

normal = { family = 'JetBrains Mono NL NF', style ='normal' }
bold = { family = 'JetBrains Mono NL NF', style ='bold' }
italic = { family = 'JetBrains Mono NL NF', style ='italic' }
bold_italic = { family = 'JetBrains Mono NL NF', style = 'bold_italic' }

# https://github.com/folke/tokyonight.nvim/blob/0283787031ef9878a2b80300de0d22e938771998/extras/alacritty/tokyonight_night.toml

[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

[colors.cursor]
cursor = '#c0caf5'
text = '#1a1b26'

[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'
